name: fresh_store_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  expandable_text: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/tabbar/bold/
    - assets/icons/tabbar/light/
    - assets/icons/light/
    - assets/icons/bold/
    - assets/icons/products/
    - assets/icons/profile/
    - assets/icons/detail/
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
        - asset: assets/fonts/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700
