name: filemanager
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  filesize: ^2.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  get: ^4.6.5
  percent_indicator: ^4.2.3
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/raster/.
    - assets/images/vector/.
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/fonts/CustomIcons.ttf
