name: tesla_mobile_app_concept
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.8.4
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.5.0
  provider: ^6.0.2
  device_preview: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GothamPro
      fonts:
        - asset: assets/fonts/GothamProBlack.ttf
          weight: 900
        - asset: assets/fonts/GothamProLight.ttf
          weight: 300
        - asset: assets/fonts/GothamProMedium.ttf
          weight: 500
        - asset: assets/fonts/GothamProRegular.ttf
          weight: 400
  