name: photoplay_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  fluttertoast: ^8.2.2
  provider: ^6.0.5
  firebase_core: ^2.8.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  flutter_native_splash: ^2.2.19
  shared_preferences: ^2.1.1
  google_sign_in: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/searchImages/
  fonts:
     - family: Gotham
       fonts:
         - asset: assets/fonts/Gotham-Bold.otf
         - asset: assets/fonts/Gotham-Book.otf
         - asset: assets/fonts/Gotham-Medium.otf

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/app_logo.png
  height: 500
  width: 500
  android_12:
    color: "#F5F5F5"
    image: assets/app_logo.png
    height: 500
    width: 500
  android: true
  ios: true